---
  region: us-west-2
  instances:
    - id: i-c8433a0f
      name: confluence
      reboot: false
      max_backups: 7
      rds:
        instance: 'confluence-rds'
        max_backups: 7
    - id: i-a9d1946e
      name: crowd
      reboot: false
      max_backups: 5
      rds:
        instance: 'crowd-rds'
        max_backups: 3
    - id: i-cc1ef30b
      name: crucible
      reboot: false
      max_backups: 7
      rds:
        instance: 'crucible-rds'
        max_backups: 3
    - id: i-820ecf45
      name: hipchat
      reboot: false
      max_backups: 7
    - id: i-701620b7
      name: jira
      reboot: false
      max_backups: 7
      rds:
        instance: 'jira-rds'
        max_backups: 3
    - id: i-694fd3ae
      name: owncloud
      reboot: false
      max_backups: 10
      rds:
        instance: 'owncloud-rds'
        max_backups: 3
