---
  region: us-west-2
  verbose: true
  rds:
    - id: 'app1-rds'
      max_backups: 14
  ec2:
    - id: i-abcd1234
      name: app1
      max_backups: 14
    - id: i-90214ee
      name: app2
      max_backups: 7
